/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connect.JavaSwingConection;
import DinhDang.Bao;
import DinhDang.Sach;
import DinhDang.TapChi;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLyThuVien extends javax.swing.JFrame {
    JavaSwingConection controlall;
    DefaultTableModel defaultTableModel;
    public void resetTableSachdata(){
        controlall = new JavaSwingConection();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }    
        };
        tabledata.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Tên NXB");
        defaultTableModel.addColumn("Số bản p/h");
        defaultTableModel.addColumn("Tên tác giả");
        defaultTableModel.addColumn("Số trang");
        List<Sach> sach=controlall.getAllSach();
        
        for (Sach i:sach)
        {
            defaultTableModel.addRow(new Object[]{i.getIdTL(),i.getTenNXB(),i.getSoBanPhatHanh()
                    ,i.getTenTacGia(),i.getSotrang()});
        } 
    }
    
    public void resetTableTapChidata(){
        controlall = new JavaSwingConection();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }    
        };
        tabledata.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Tên NXB");
        defaultTableModel.addColumn("Số bản p/h");
        defaultTableModel.addColumn("Số phát hành");
        defaultTableModel.addColumn("Tháng phát hành");
    
        List<TapChi> tapchi=controlall.getAllTapChi();
        
        for (TapChi i:tapchi)
        {
            defaultTableModel.addRow(new Object[]{i.getIdTL(),i.getTenNXB(),i.getSoBanPhatHanh()
                    ,i.getSoPhatHanh(),i.getThangPhatHanh()});
        }
    }
    
    public void resetTableBaodata(){
        controlall = new JavaSwingConection();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }    
        };
        tabledata.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Tên NXB");
        defaultTableModel.addColumn("Số bản p/h");
        defaultTableModel.addColumn("Ngày Phát Hành");
    
        List<Bao> bao=controlall.getAllBao();
        
        for (Bao i:bao)
        {
            defaultTableModel.addRow(new Object[]{i.getIdTL(),i.getTenNXB(),i.getSoBanPhatHanh()
                    ,i.getNgayPhatHanh()});
        } 
    }/**
     * Creates new form QuanLyThuVien
     */
    public QuanLyThuVien() {
        initComponents();
        resetTableSachdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuttapchi = new javax.swing.JButton();
        nutsach = new javax.swing.JButton();
        nutbao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        xoabutton = new javax.swing.JButton();
        timbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuttapchi.setText("Tạp Chí");
        nuttapchi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuttapchiActionPerformed(evt);
            }
        });

        nutsach.setText("Sách");
        nutsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsachActionPerformed(evt);
            }
        });

        nutbao.setText("Báo");
        nutbao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutbaoActionPerformed(evt);
            }
        });

        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabledata);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jButton1.setText("Thêm");
        jPanel1.add(jButton1);

        xoabutton.setText("Xóa");
        xoabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabuttonActionPerformed(evt);
            }
        });
        jPanel1.add(xoabutton);

        timbutton.setText("Tìm");
        timbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(timbutton);

        exitbutton.setText("Thoát");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(exitbutton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(nutsach, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(nuttapchi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(nutbao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuttapchi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nutbao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nutsach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nutsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsachActionPerformed
        resetTableSachdata();        // TODO add your handling code here:
    }//GEN-LAST:event_nutsachActionPerformed

    private void nuttapchiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuttapchiActionPerformed
        resetTableTapChidata();        // TODO add your handling code here:
    }//GEN-LAST:event_nuttapchiActionPerformed

    private void nutbaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutbaoActionPerformed
        resetTableBaodata();        // TODO add your handling code here:
    }//GEN-LAST:event_nutbaoActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void timbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timbuttonActionPerformed
         String x=JOptionPane.showInputDialog(null,"Nhập mã tài liệu cần tìm");
        if (x==null) System.out.print("");
        else if (controlall.searchTaiLieu(x)==null)
        {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã "+x+" trong danh sách", "Tìm", JOptionPane.INFORMATION_MESSAGE);
        }
        else 
        {
            new Tim(controlall.searchTaiLieu(x)).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_timbuttonActionPerformed

    private void xoabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabuttonActionPerformed
        int row = tabledata.getSelectedRow();
        String id="";
        if (row == -1) {
            String x=JOptionPane.showInputDialog(null,"Nhập mã tài liệu cần xóa");
            if (x==null) System.out.print("");
            else {
                id=x;
                controlall.deteleTaiLieu(x); 
            }  
        }
        else 
        {
            id+=String.valueOf(tabledata.getValueAt (row, 0));
            int confirm = JOptionPane.showConfirmDialog(this, "Ban chac chan muon xoa khong?");
            if (confirm == JOptionPane. YES_OPTION) 
            {
                String userId =String.valueOf(tabledata.getValueAt (row, 0));
                controlall.deteleTaiLieu(userId);
            }
        } 
//        defaultTableModel.setRowCount(0);
        if (id.length()>4) {
             if (id.substring(0,1).equals("S")) resetTableSachdata();
            else if (id.substring(0,1).equals("T")) resetTableTapChidata();
            else if (id.substring(0,1).equals("B")) resetTableBaodata();
            else resetTableSachdata();
        }
    }//GEN-LAST:event_xoabuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThuVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nutbao;
    private javax.swing.JButton nutsach;
    private javax.swing.JButton nuttapchi;
    private javax.swing.JTable tabledata;
    private javax.swing.JButton timbutton;
    private javax.swing.JButton xoabutton;
    // End of variables declaration//GEN-END:variables
}
